Add controllers
volkovask/java-shareit pull request #1
Opened 2023-01-07 16:50 UTC by volkovask

2023-01-09 12:22 UTC, AnastasiyaFomkina requested changes

2023-01-09 12:22 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            return List.of();
Можно использовать `Collections.emptyList()` для создания пустых списков, чтобы улучшить читаемость кода. А так между ними разницы никакой нет

2023-01-09 14:55 UTC, volkovask commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>   */
Исправлено.

2023-01-09 15:03 UTC, volkovask commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +import lombok.*;
Исправлено.

2023-01-09 15:11 UTC, volkovask commented on src/main/java/ru/practicum/shareit/exception/controller/ErrorHandler.java
> +    public ErrorResponse handleIncorrectParameterException(final IncorrectParameterException e) {
Исправлено.

2023-01-09 15:11 UTC, volkovask commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +            @RequestHeader("X-Sharer-User-Id") Long ownerId) {
Исправлено.

2023-01-09 15:43 UTC, volkovask commented on src/main/java/ru/practicum/shareit/item/controller/ItemController.java
> +        itemDto.setOwner(ownerId);
Исправлено.

2023-01-09 15:45 UTC, volkovask commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            return List.of();
Исправлено.

2023-01-09 16:33 UTC, volkovask commented on src/main/java/ru/practicum/shareit/user/repository/UserRepositoryImpl.java
> +        for (User userCheck : users.values()) {
Исправлено.

2023-01-09 16:40 UTC, volkovask commented
Анастасия, привет. :)
Спасибо за ревью.

2023-01-10 10:16 UTC, AnastasiyaFomkina approved these changes
Отличная работа, молодец 👍

2023-01-10 13:46 UTC, merged